### ISSUE TITLE
My app keeps crashing in. release mode

### ISSUE THREAD

**Issue by cokariinc** [qonversion/flutter-sdk#120]
The app works fine in debug mode but crashes in release mode with this log. I really can't make anything of it
```
FATAL EXCEPTION: main
E/AndroidRuntime(16123): Process: com.example.app, PID: 16123
E/AndroidRuntime(16123): java.lang.IllegalArgumentException: Unable to create call adapter for interface m.g
E/AndroidRuntime(16123):     for method Api.init
E/AndroidRuntime(16123):        at m.Y.c(Unknown Source:43)
E/AndroidRuntime(16123):        at m.Y.a(:71)
E/AndroidRuntime(16123):        at m.X.c(Unknown Source:29)
E/AndroidRuntime(16123):        at m.V.invoke(Unknown Source:32)
E/AndroidRuntime(16123):        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime(16123):        at $Proxy3.init(Unknown Source)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QonversionRepository.initRequest(Unknown Source:38)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QonversionRepository.init(Unknown Source:34)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QProductCenterManager.processInit(Unknown Source:17)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QProductCenterManager.access$processInit(Unknown Source:0)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QProductCenterManager$continueLaunchWithPurchasesInfo$1.invoke(Unknown Source:36)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.QProductCenterManager$continueLaunchWithPurchasesInfo$1.invoke(Unknown Source:2)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService$queryPurchases$1$1.invoke(Unknown Source:76)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService$queryPurchases$1$1.invoke(Unknown Source:2)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService.withReadyClient(Unknown Source:14)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService.access$withReadyClient(Unknown Source:0)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService$queryPurchases$1.invoke(Unknown Source:9)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService$queryPurchases$1.invoke(Unknown Source:2)
E/AndroidRuntime(16123):        at com.qonversion.android.sdk.billing.QonversionBillingService$executeRequestsFromQueue$1$1$1.run(Unknown Source:3)
E/AndroidRuntime(16123):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(16123):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16123):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(16123):        at android.app.ActivityThread.main(ActivityThread.java:6705)
E/AndroidRuntime(16123):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16123):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(16123):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/AndroidRuntime(16123): Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
E/AndroidRuntime(16123):        at m.d0.e(Unknown Source:16)
E/AndroidRuntime(16123):        at m.t.a(:2)
E/AndroidRuntime(16123):        at m.X.a(:1)
E/AndroidRuntime(16123):        at m.Y.a(:1)
E/AndroidRuntime(16123):
```

**Comment by Maria-Bordunova** [comment]
Hi @cokariinc . Could you please provide the SDK version you are using?

**Comment by cokariinc** [comment]
qonversion_flutter: ^4.2.0 @Maria-Bordunova

**Comment by cokariinc** [comment]
It crashed on both devices I tried it on. Blackview A80pro, Doogee S60.

**Comment by Maria-Bordunova** [comment]
@cokariinc We and our clients don't observe such behaviour in the release mode. Do you have other Google devices/emulators(Pixel, Nexus, Samsung, etc.) to test? It seems to me the issue is related to the particular devices.

**Comment by cokariinc** [comment]
@Maria-Bordunova I found the source of the issue. This was happening because I was passing an empty string to **Qonversion.identify**, thanks for your help.
