### ISSUE TITLE
StrictMode policy violation on Google Play prelaunch report

### ISSUE THREAD

**Issue by kobeumut** [qonversion/flutter-sdk#95]
We used your new SDK which version of 4.0.0 but we have got same issue on Google Play prelaunch report. 

`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at n.g0.k.e.b(Unknown Source:1)
	at n.g0.k.e.a(Unknown Source:7)
	at n.g0.k.e.d(Unknown Source:4)
	at n.g0.k.e.e(Unknown Source:0)
	at n.g0.k.a.g(Unknown Source:21)
	at n.g0.f.c.f(Unknown Source:62)
	at n.g0.f.c.j(Unknown Source:52)
	at n.g0.f.c.d(Unknown Source:178)
	at n.g0.f.g.f(Unknown Source:221)
	at n.g0.f.g.g(Unknown Source:0)
	at n.g0.f.g.i(Unknown Source:22)
	at n.g0.f.a.intercept(Unknown Source:25)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.g0.e.a.intercept(Unknown Source:124)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.g0.g.a.intercept(Unknown Source:161)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.j.intercept(Unknown Source:48)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at com.qonversion.android.sdk.api.NetworkInterceptor.intercept(Unknown Source:85)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.z.e(Unknown Source:115)
	at n.z$b.k(Unknown Source:10)
	at n.g0.b.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)`

and also show second error:

`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at n.g0.k.e.b(Unknown Source:1)
	at n.g0.k.e.a(Unknown Source:7)
	at n.g0.k.e.d(Unknown Source:4)
	at n.g0.k.e.e(Unknown Source:0)
	at n.g0.k.a.g(Unknown Source:12)
	at n.g0.f.c.f(Unknown Source:62)
	at n.g0.f.c.j(Unknown Source:52)
	at n.g0.f.c.d(Unknown Source:178)
	at n.g0.f.g.f(Unknown Source:221)
	at n.g0.f.g.g(Unknown Source:0)
	at n.g0.f.g.i(Unknown Source:22)
	at n.g0.f.a.intercept(Unknown Source:25)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.g0.e.a.intercept(Unknown Source:124)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.g0.g.a.intercept(Unknown Source:161)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.j.intercept(Unknown Source:48)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at com.qonversion.android.sdk.api.NetworkInterceptor.intercept(Unknown Source:85)
	at n.g0.g.g.j(Unknown Source:167)
	at n.g0.g.g.c(Unknown Source:6)
	at n.z.e(Unknown Source:115)
	at n.z$b.k(Unknown Source:10)
	at n.g0.b.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)`

**Comment by Maria-Bordunova** [comment]
Hi, @kobeumut . You said the "same". It means you had it not only on 4.0.0 version?

**Comment by kobeumut** [comment]
Yes, that's true, I used it before version 3 but prelaunch report the same error sends to the google play reporting section.

**Comment by Maria-Bordunova** [comment]
@kobeumut 
Oh, I can see these warnings as well on Google Console for the sample app with our SDK. 
Could you tell me whether it blocks you from release on Google Play?

It's unpleasant to see such warnings, so we will do that as soon as possible

**Comment by kobeumut** [comment]
Hi @Maria-Bordunova, the app already is in release. It doesn't block us but, I don't know how to affect our subscription status.

**Comment by Maria-Bordunova** [comment]
Hi @kobeumut! Sorry for the long response here :pray:
We fixed the issue and released new [sdk version 4.1.1](https://github.com/qonversion/flutter-sdk/releases/tag/4.1.1).
Don't hesitate to ask if you still have questions.
